-- Feed grids draw a small preview generated by the client at upload time
-- instead of the full attachment. Rows written before this migration (and
-- backup imports) keep NULL here, and the image endpoint falls back to the
-- original bytes for them.
ALTER TABLE memo_images ADD COLUMN thumb_mime TEXT;
ALTER TABLE memo_images ADD COLUMN thumb_base64 TEXT;
